[package]
name = "hyprland"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
smol = "2.0.2"
thiserror = { git = "https://github.com/onlycs/thiserror", version = "2.0.11" }
