[package]
name = "gnyprland-relay"
version = "0.1.0"
edition = "2024"

[dependencies]
smol = "2.0.2"
strum = { version = "0.27.1", features = ["derive"] }
thiserror = { git = "https://github.com/onlycs/thiserror", version = "2.0.11" }
